Notes about interesting features

In [2]:
7 \ 42 # inverse divide

6.0

In [59]:
eps(25.), nextfloat(1.), prevfloat(0.)

(3.552713678800501e-15, 1.0000000000000002, -5.0e-324)

In [61]:
typeof(big(50)), typeof(big(100.0))

(BigInt, BigFloat)

In [63]:
zero(1), typeof(zero(1)), one(Float64)

(0, Int64, 1.0)

In [34]:
x = 3
2x^2 - 3x + 1

10

In [36]:
2^2x

64

The precedence of numeric literal coefficients is the same as that of unary operators such as negation. So 2^3x is parsed as 2^(3x), and 2x^3 is parsed as 2*(x^3).

In [37]:
2(x-1)^2 - 3(x-1) + 1

3

In [39]:
true ⊻ false # \xor, alternative: xor(x, y)

true

In [43]:
A = [5,4,3]
2 .* A.^2 .+ sin.(A)

3-element Array{Float64,1}:
 49.0411
 31.2432
 18.1411

In [44]:
@. 2A^2 + sin(A)

3-element Array{Float64,1}:
 49.0411
 31.2432
 18.1411

In [45]:
 @. sqrt(abs($sort(A))) # equivalent to sqrt.(abs.(sort(x)))

3-element Array{Float64,1}:
 1.73205
 2.0    
 2.23607

In [48]:
[1 NaN] == [1 NaN] # NaN ≠ NaN

false

In [49]:
isequal([1 NaN],[1 NaN])

true

In [50]:
-0.0 == 0.0

true

In [51]:
isequal(-0.0, 0.0)

false

In [52]:
 1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [54]:
A = [0, 0.5, 1]
0 .< A .< 1

3-element BitArray{1}:
 false
  true
 false

the order of evaluations in a chained comparison is undefined. It is strongly recommended not to use expressions with side effects...

In [55]:
5//8 + 3//4

11//8

In [56]:
[1:5;] |> x->x.^2 |> sum |> inv

0.01818181818181818

In [57]:
Float64 <: AbstractFloat

true

In [64]:
Base.operator_precedence(:+), 
Base.operator_precedence(:*), 
Base.operator_precedence(:.)

(9, 11, 15)

In [65]:
Int(16.8)

LoadError: InexactError()

In [66]:
round(Int, 16.8)

17

In [67]:
round(DateTime(2013, 2, 13, 0, 31, 20), Dates.Minute(15))

2013-02-13T00:30:00

In [68]:
mod(5,5), mod1(5,5), mod(0,5), mod1(0,5)

(0, 5, 0, 5)

In [69]:
mod2pi(9*pi/4)

0.7853981633974481

In [70]:
gcd(6,9), lcm(2,3)

(3, 6)

In [71]:
∛3 # \cbrt

1.4422495703074083

In [72]:
hypot(2, 3)

3.6055512754639896

In [73]:
significand(15.2)/15.2

0.125

In [74]:
?sinpi

search: sinpi



```
sinpi(x)
```

Compute $\sin(\pi x)$ more accurately than `sin(pi*x)`, especially for large `x`.


In order to compute trigonometric functions with degrees instead of radians, suffix the function with d. For example, sind(x) computes the sine of x where x is specified in degrees. 

In [76]:
real(1 + 2im), imag(1 + 2im), conj(1 + 2im)

(1, 2, 1 - 2im)

In [77]:
numerator(2//3), denominator(2//3)

(2, 3)

### Strings

In [83]:
'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [81]:
typeof(ans)

Char

In [86]:
Int('x'), typeof(Int('x'))

(120, Int64)

In [88]:
Char(0x110000) # no automatic check

'\U110000': Unicode U+110000 (category Cn: Other, not assigned)

In [90]:
isvalid(Char, 0x110000)

false

In [93]:
'A' < 'a', 'x' - 'a', 'A' + 1

(true, 23, 'B')

In [94]:
"""Contains "quote" characters"""

"Contains \"quote\" characters"

In [99]:
str = "Hello, world.\n"
str[1], str[end], str[end-1], str[end÷2], str[4:9], str[2:2]

('H', '\n', '.', ' ', "lo, wo", "e")

In [100]:
# ↑ note type Char for single indices

#### Iteration

In [101]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [103]:
s[1]

'∀': Unicode U+2200 (category Sm: Symbol, math)

In [102]:
s[2]

LoadError: UnicodeError: invalid character index

In [104]:
nextind(s,1)

4

In [107]:
for i = 1:endof(s)
   try
       print(s[i])
   catch
       # ignore the index error
   end
end

∀ x ∃ y

In [106]:
# iterating handles invalid indices
for c in s
   print(c)
end

∀ x ∃ y

#### Concatenation & Interpolation

In [111]:
# Concatenation
greet = "Hello"; whom = "world"

"world"

In [109]:
string(greet, ", ", whom, ".\n")

"Hello, world.\n"

In [110]:
greet * ", " * whom * ".\n"

"Hello, world.\n"

In [112]:
"$greet, $whom.\n"

"Hello, world.\n"

In [113]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [116]:
print("I have \$100 in my account.\n")

I have $100 in my account.


#### Triple-quotes

In [117]:
"""
hello""" # NOTE: 1 newline stripped, not more

"hello"

In [125]:
# Triple-quoted strings are also dedented to the level 
# of the least-indented line. 
str = """
    Hello,
    world.
  """ # -> those whitespaces at the beginning count

"  Hello,\n  world.\n"

####

In [126]:
"abracadabra" < "xylophone"

true

In [128]:
search("xylophone", 'x'), search("xylophone", 'o', 5)

(1, 7)

In [130]:
contains("Hello, world.", "world")

true

In [131]:
'o' in "xylophone"  # required for Char

true

In [132]:
?count

search: count countnz countlines count_ones count_zeros codeunit checkbounds



```
count(p, itr) -> Integer
count(itr) -> Integer
```

Count the number of elements in `itr` for which predicate `p` returns `true`. If `p` is omitted, counts the number of `true` elements in `itr` (which should be a collection of boolean values).

```jldoctest
julia> count(i->(4<=i<=6), [2,3,4,5,6])
3

julia> count([true, false, true, true])
3
```


In [133]:
repeat(".:Z:.", 10)

".:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:."

In [134]:
join(["apples", "bananas", "pineapples"], ", ", " and ")

"apples, bananas and pineapples"

In [138]:
?less

search: less @less isless lexless filesize values falses sylvester



```
less(file::AbstractString, [line::Integer])
```

Show a file using the default pager, optionally providing a starting line number. Returns to the `julia` prompt when you quit the pager.

```
less(function, [types])
```

Show the definition of a function using the default pager, optionally specifying a tuple of types to indicate which method to see.


#### Regex

In [140]:
r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [141]:
typeof(ans)

Regex

In [142]:
ismatch(r"^\s*(?:#|$)", "not a comment")

false

In [143]:
match(r"^\s*(?:#|$)", "# a comment")

RegexMatch("#")

In [152]:
m = match(r"^\s*(?:#|$)", "not a comment")

In [153]:
typeof(m)

Void

In [154]:
m == nothing

true

In [155]:
match(r"a+.*b+.*?d$"ism, "Goodbye,\nOh, angry,\nBad world\n")

RegexMatch("angry,\nBad world")

In [156]:
r"""..."""

r"..."

####

In [158]:
show(b"DATA\xff\u2200")

UInt8[0x44, 0x41, 0x54, 0x41, 0xff, 0xe2, 0x88, 0x80]

In [159]:
"DATA\xff\u2200"

LoadError: syntax: invalid UTF-8 sequence

In [163]:
v = v"0.2.1-rc1+win64"

v"0.2.1-rc1+win64"

In [164]:
typeof(v)

VersionNumber

In [166]:
v.major, v.minor, v.patch

(0, 2, 1)

In [167]:
v"0.2" <= VERSION < v"0.3-"

false

In [168]:
VERSION

v"0.6.0"

In [169]:
raw"\n\nasd"

"\\n\\nasd"

In [170]:
raw"\""

"\""

In [171]:
raw"""   " """

"   \" "

In [173]:
'a':'z' |> Array |> show

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In the assignment form, the body of the function must be a single expression, although it can be a compound expression

### Call external programs (shell)

In [175]:
`echo hello`

`echo hello`

In [177]:
`echo Hello` |> run

Hello


In [179]:
b = readstring(`echo hello`)

"hello\n"

### Functions

In [180]:
a(b) = b^2
a(16)

256

In [182]:
?hcat # vcat, hvcat

search: hcat hvcat showcompact @threadcall catch_backtrace catch_stacktrace



```
hcat(A...)
```

Concatenate along dimension 2.

```jldoctest
julia> a = [1; 2; 3; 4; 5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> b = [6 7; 8 9; 10 11; 12 13; 14 15]
5×2 Array{Int64,2}:
  6   7
  8   9
 10  11
 12  13
 14  15

julia> hcat(a,b)
5×3 Array{Int64,2}:
 1   6   7
 2   8   9
 3  10  11
 4  12  13
 5  14  15

julia> c = ([1; 2; 3], [4; 5; 6])
([1, 2, 3], [4, 5, 6])

julia> hcat(c...)
3×2 Array{Int64,2}:
 1  4
 2  5
 3  6
```


In [183]:
v = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [184]:
v' # ctranspose

1×3 RowVector{Int64,Array{Int64,1}}:
 1  2  3

In [185]:
v.' # transpose

1×3 RowVector{Int64,Array{Int64,1}}:
 1  2  3

In [186]:
1:42 == colon(1, 42)

true

In [190]:
v[1] == getindex(v, 1) # also: setindex!()

true

In [189]:
function(x)
   x^2 + 2x - 1
end
# same as x -> x^2 + 2x - 1

(::#21) (generic function with 1 method)

In [191]:
(x,y,z)->2x+y-z

(::#23) (generic function with 1 method)

In [192]:
()->3

(::#25) (generic function with 1 method)

In [193]:
foo(a,b) = a+b, a*b
x, y = foo(2,3)

(5, 6)

In [196]:
bar(a,b,x...) = (a,b,x)
bar(1, 2, 3, 4)

(1, 2, (3, 4))

In [199]:
x = (3, 4)
bar(1,2,x...)

(1, 2, (3, 4))

In [201]:
x = (2, 3, 4)
bar(1,x...)

(1, 2, (3, 4))

In [202]:
x = [3,4]; bar(1,2,x...)

(1, 2, (3, 4))

In [207]:
baz(a,b) = a + b;
baz(x...)

7

In [209]:
g(a=10) = a/2
g()

5.0

In [211]:
#Functions with keyword arguments are defined using a semicolon 
#in the signature:
function plot(x, y; style="solid", width=1, color="black")
    ###
end

plot (generic function with 1 method)

In [217]:
# all equivalent:
plot(x, y, width=2)
plot(x, y; width=2) 
plot(x, y; (:width,2)) 
plot(x, y; :width => 2)

In [215]:
function f(;x::Int64=1) end

f (generic function with 1 method)

In [216]:
function f(x; y=0, kwargs...) end

f (generic function with 2 methods)

Left to right evaluation of kwargs - latest wins if duplicates

When optional argument default expressions are evaluated, only previous arguments are in scope. In contrast, all the arguments are in scope when keyword arguments default expressions are evaluated. 

In [219]:
h(a, b=a*2) = b
h(2)

4

In [222]:
map([1,2,3]) do x
   x^2
end |> show

[1, 4, 9]

In [ ]:
open("outfile.txt", "w") do io
    write(io, data)
end

In [225]:
sc = sort ∘ collect
sc("cfab") |> show

['a', 'b', 'c', 'f']

In [226]:
is_sth(b) = b
negated = !is_sth
negated(true)

false

### Control Flow

In [227]:
z = (x = 1; y = 2; x + y) # same as begin...end

3

In [233]:
x=1
p = if x > 0
   "positive!"
else
   "negative..."
end

"positive!"

In [234]:
if 1
   println("true")
end

LoadError: TypeError: non-boolean (Int64) used in boolean context

In [235]:
for i = 1:2, j = 3:4
   println((i, j))
end

(1, 3)
(1, 4)
(2, 3)
(2, 4)


In [236]:
struct MyCustomException <: Exception end

In [237]:
info("Hi")
warn("Hi")

INFO: Hi


In [238]:
sqrt_second(x) = try
   sqrt(x[2])
catch y
   if isa(y, DomainError)
       sqrt(complex(x[2], 0))
   elseif isa(y, BoundsError)
       sqrt(x)
   end
end

sqrt_second (generic function with 1 method)

In [239]:
try error() end # No catch! Returns nothing

`rethrow()`, `backtrace()`, `catch_backtrace()`

In [ ]:
f = open("file")
try
    # operate on file f
finally
    close(f)
end

In [241]:
eye(4,4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [242]:
eye([1 2 ; 3 4])

2×2 Array{Int64,2}:
 1  0
 0  1

#### Tasks

In [245]:
chnl = Channel(c->foreach(i->put!(c,i), 1:4))
chnl |> collect |> show

Any[1, 2, 3, 4]

In [247]:
function mytask(myarg)
    myarg ^ 2
end

taskHdl = Task(() -> mytask(7))
taskHdl = @task mytask(7)

Task (runnable) @0x000000012344e890

In [249]:
schedule(taskHdl)

Task (done) @0x000000012344e890

Note that currently Julia tasks are not scheduled to run on separate CPU cores. True kernel threads are discussed under the topic of Parallel Computing.

### Scope of variables

In [250]:
x = 0;
for i = 1:10
   local x
   x = i + 1
end
x

0

In [251]:
for i = 1:10
   global z
   z = i
end
z

10

In [257]:
workspace()

In [258]:
f = y -> y + a

(::#1) (generic function with 1 method)

In [259]:
f(3)

LoadError: UndefVarError: a not defined

In [260]:
a = 1
f(3)

4

In [262]:
iseven(2), isodd(2)

(true, false)

In [270]:
const e  = 2.71828182845904523536;

If a global variable will not change, adding a const declaration solves this performance problem.

Local constants are quite different. The compiler is able to determine automatically when a local variable is constant, so local constant declarations are not necessary for performance purposes.

---
Note that const only affects the variable binding; the variable may be bound to a mutable object (such as an array), and that object may still be modified.

### Types

concrete types may not subtype each other: all concrete types are final and may only have abstract types as their supertypes.
...
There is no meaningful concept of a "compile-time type"
...
Only values, not variables, have types – variables are simply names bound to values.

In [271]:
isbits(Complex{Float64}), isbits(Complex)

(true, false)

When appended to an expression computing a value, the :: operator is read as "is an instance of"

In [272]:
(1+2)::AbstractFloat

LoadError: TypeError: typeassert: expected AbstractFloat, got Int64

In [273]:
(1+2)::Int

3

In [278]:
function foo()
    x::Int8 = 100 # not assert, but convert!
    #x = 300 -> InexactError()
    x
end
foo()

100

In [279]:
function sinc(x)::Float64
    if x == 0
        return 1
    end
    return sin(pi*x)/(pi*x)
end
# Returning from this function behaves just like an 
# assignment to a variable with a declared type: 
# the value is always converted to Float64.

sinc (generic function with 1 method)

Any is commonly called "top" because it is at the apex of the type graph. Julia also has a predefined abstract "bottom" type, at the nadir of the type graph, which is written as Union{}. It is the exact opposite of Any: no object is an instance of Union{} and all types are supertypes of Union{}.

In [280]:
function showtypetree(T, level=0)
    println("\t" ^ level, T)
    for t in subtypes(T)
        if t != Any
            showtypetree(t, level+1)
        end
   end
end
showtypetree(Number)

Number
	Complex
	Real
		AbstractFloat
			BigFloat
			Float16
			Float32
			Float64
		Integer
			BigInt
			Bool
			Signed
				Int128
				Int16
				Int32
				Int64
				Int8
			Unsigned
				UInt128
				UInt16
				UInt32
				UInt64
				UInt8
		Irrational
		Rational


In [281]:
Integer <: Number

true

In [283]:
abstract type MyReal     <: Number end
abstract type MyNumber end  # default supertype: Any

An important point to note is that there is no loss in performance if the programmer relies on a function whose arguments are abstract types, because it is recompiled for each tuple of argument concrete types with which it is invoked. (There may be a performance issue, however, in the case of function arguments that are containers of abstract types; see Performance Tips.)

In [285]:
primitive type MFloat16 <: AbstractFloat 16 end
primitive type MChar 32 end

 In Julia, all values are objects, but functions are not bundled with the objects they operate on. This is necessary since Julia chooses which method of a function to use by multiple dispatch, meaning that the types of all of a function's arguments are considered when selecting a method, rather than just the first one

In [288]:
workspace()

In [289]:
struct Foo
   bar
   baz::Int
   qux::Float64
end

In [290]:
foo = Foo("Hello, world.", 23, 1.5)

Foo("Hello, world.", 23, 1.5)

In [291]:
foo |> typeof

Foo

 Two constructors are generated automatically (these are called default constructors). One accepts any arguments and calls convert() to convert them to the types of the fields, and the other accepts arguments that match the field types exactly.

In [293]:
(), typeof(())

((), Tuple{})

In [295]:
fieldnames(foo) |> show

Symbol[:bar, :baz, :qux]

Composite objects declared with struct are immutable; they cannot be modified after construction.

An immutable object might contain mutable objects, such as arrays, as fields. Those contained objects will remain mutable

Composite types with no fields are singletons; there can be only one instance of such types:

In [297]:
struct NoFields end
NoFields() === NoFields()

true

In [298]:
mutable struct Bar; baz; qux::Float64; end
bar = Bar("Hello", 1.5);
bar.qux = 2.0
bar.baz = 1//2

1//2

In order to support mutation, such objects are generally allocated on the heap, and have stable memory addresses.

An object with an immutable type is passed around (both in assignment statements and in function calls) by copying, whereas a mutable type is passed around by reference.

In [299]:
struct Supertyped <: Number; end 

In [300]:
typeof(Int), typeof(Supertyped), typeof(Bar)

(DataType, DataType, DataType)

A DataType may be abstract or concrete. If it is concrete, it has a specified size, storage layout, and (optionally) field names. 

In [301]:
IntOrString = Union{Int,AbstractString}

Union{AbstractString, Int64}

In [303]:
1 :: IntOrString, "Hello!" :: IntOrString

(1, "Hello!")

In [304]:
1.0 :: IntOrString

LoadError: TypeError: typeassert: expected Union{AbstractString, Int64}, got Float64

#### Parametric Composite Types

In [305]:
struct Point{T}
   x::T
   y::T
end

In [308]:
Point(2,"H")

LoadError: MethodError: no method matching Point(::Int64, ::String)
Closest candidates are:
  Point(::T, ::T) where T at In[305]:2

In [309]:
Point{Float64} <: Point

true

In [310]:
Point{Float64} <: Point{Real}

false

In [311]:
Float64 <: Real # !!

true

Julia's type parameters are invariant, rather than being covariant (or even contravariant). This is for practical reasons: while any instance of Point{Float64} may conceptually be like an instance of Point{Real} as well, the two types have different representations in memory:
* An instance of Point{Float64} can be represented compactly and efficiently as an immediate pair of 64-bit values;
* An instance of Point{Real} must be able to hold any pair of instances of Real. Since objects that are instances of Real can be of arbitrary size and structure, in practice an instance of Point{Real} must be represented as a pair of pointers to individually allocated Real objects.

In [313]:
# To make Point{Float64} as arg work:
function norm(p::Point{<:Real})
    sqrt(p.x^2 + p.y^2)
end

norm (generic function with 1 method)

In [315]:
Point{Float64}(1.0, 2.0), Point(1.0,2.0)

(Point{Float64}(1.0, 2.0), Point{Float64}(1.0, 2.0))

In [316]:
Point(1,2.5)

LoadError: MethodError: no method matching Point(::Int64, ::Float64)
Closest candidates are:
  Point(::T, ::T) where T at In[305]:2

In [317]:
abstract type Pointy{T} end

The notation `Pointy{<:Real}` can be used to express the Julia analogue of a covariant type, while `Pointy{>:Int}` the analogue of a contravariant type, but technically these represent sets of types (see UnionAll Types).

In [320]:
abstract type Pointy2{T<:Real} end

In [321]:
struct MyRational{T<:Integer} <: Real
    num::T
    den::T
end

Tuple types are covariant in their parameters: Tuple{Int} is a subtype of Tuple{Any}. Therefore Tuple{Any} is considered an abstract type, and tuple types are only concrete if their parameters are.

In [322]:
mytupletype = Tuple{AbstractString,Vararg{Int}}

Tuple{AbstractString,Vararg{Int64,N} where N}

In [323]:
mytupletype2 = Tuple{AbstractString,Vararg{Int, 3}}

Tuple{AbstractString,Int64,Int64,Int64}

In [324]:
isa(Float64, Type{Float64})

true

`Type{T}` is a singleton type

In [325]:
primitive type MyPtr{T} 32 end

In [326]:
Array{T,N} where N where T

Array{T,N} where N where T

In [327]:
# A{B,C} is equivalent to A{B}{C} 

In [328]:
Array{T} where T<:Integer 

Array{T,N} where N where T<:Integer

In [329]:
Array{<:Integer}

Array{#s16,N} where N where #s16<:Integer

In [330]:
Array{T} where Int<:T<:Number

Array{T,N} where N where Int64<:T<:Number

In [331]:
Array{>:Int}

Array{#s17,N} where N where #s17>:Int64

In [337]:
f() = begin
    a::Array{>:Int} = [Int8(1)]
    a
end
f()

LoadError: MethodError: Cannot `convert` an object of type Array{Int8,1} to an object of type Array{#s20,N} where N where #s20>:Int64
This may have arisen from a call to the constructor Array{#s20,N} where N where #s20>:Int64(...),
since type constructors fall back to convert methods.

In [338]:
Vector{T} = Array{T,1}

Array{T,1} where T

In [339]:
if Int === Int64
    const UInt = UInt64
else
    const UInt = UInt32
end

UInt64

In [340]:
typeof(Union{Real,Float64,Rational})

DataType

In [341]:
typeof(Union{Real,String})

Union

In [342]:
typeof(DataType)

DataType

In [343]:
supertype(Float64)

AbstractFloat

In [344]:
supertype(Any)

Any

In [345]:
supertype(Union{Float64,Int64})

LoadError: MethodError: no method matching supertype(::Type{Union{Float64, Int64}})
Closest candidates are:
  supertype(::DataType) at operators.jl:41
  supertype(::UnionAll) at operators.jl:46

#### Custom pretty printing

In [346]:
struct Polar{T<:Real} <: Number
   r::T
   Θ::T
end
Polar(r::Real,Θ::Real) = Polar(promote(r,Θ)...)

Polar

In [349]:
Base.show(io::IO, z::Polar) = 
    print(io, z.r, " * exp(", z.Θ, "im)")

In [350]:
Polar(1, 2)

1 * exp(2im)

In [356]:
Base.show{T}(io::IO, ::MIME"text/plain", z::Polar{T}) =
           print(io, "Polar{$T} complex number:\n   ", z)
# -> not working in IJulia...

In [360]:
# but this should:
Base.show{T}(io::IO, ::MIME"text/html", z::Polar{T}) =
           println(io, "<code>Polar{$T}</code> complex number: ",
                   z.r, " <i>e</i><sup>", z.Θ, " <i>i</i></sup>")

In [363]:
Polar(1, 2)

1 * exp(2im)

In [364]:
show(STDOUT, "text/html", Polar(3.0,4.0))

<code>Polar{Float64}</code> complex number: 3.0 <i>e</i><sup>4.0 <i>i</i></sup>
