Notes about interesting features

In [2]:
7 \ 42 # inverse divide

6.0

In [59]:
eps(25.), nextfloat(1.), prevfloat(0.)

(3.552713678800501e-15, 1.0000000000000002, -5.0e-324)

In [61]:
typeof(big(50)), typeof(big(100.0))

(BigInt, BigFloat)

In [63]:
zero(1), typeof(zero(1)), one(Float64)

(0, Int64, 1.0)

In [34]:
x = 3
2x^2 - 3x + 1

10

In [36]:
2^2x

64

The precedence of numeric literal coefficients is the same as that of unary operators such as negation. So 2^3x is parsed as 2^(3x), and 2x^3 is parsed as 2*(x^3).

In [37]:
2(x-1)^2 - 3(x-1) + 1

3

In [39]:
true ⊻ false # \xor, alternative: xor(x, y)

true

In [43]:
A = [5,4,3]
2 .* A.^2 .+ sin.(A)

3-element Array{Float64,1}:
 49.0411
 31.2432
 18.1411

In [44]:
@. 2A^2 + sin(A)

3-element Array{Float64,1}:
 49.0411
 31.2432
 18.1411

In [45]:
 @. sqrt(abs($sort(A))) # equivalent to sqrt.(abs.(sort(x)))

3-element Array{Float64,1}:
 1.73205
 2.0    
 2.23607

In [48]:
[1 NaN] == [1 NaN] # NaN ≠ NaN

false

In [49]:
isequal([1 NaN],[1 NaN])

true

In [50]:
-0.0 == 0.0

true

In [51]:
isequal(-0.0, 0.0)

false

In [52]:
 1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [54]:
A = [0, 0.5, 1]
0 .< A .< 1

3-element BitArray{1}:
 false
  true
 false

the order of evaluations in a chained comparison is undefined. It is strongly recommended not to use expressions with side effects...

In [55]:
5//8 + 3//4

11//8

In [56]:
[1:5;] |> x->x.^2 |> sum |> inv

0.01818181818181818

In [57]:
Float64 <: AbstractFloat

true

In [64]:
Base.operator_precedence(:+), 
Base.operator_precedence(:*), 
Base.operator_precedence(:.)

(9, 11, 15)

In [65]:
Int(16.8)

LoadError: InexactError()

In [66]:
round(Int, 16.8)

17

In [67]:
round(DateTime(2013, 2, 13, 0, 31, 20), Dates.Minute(15))

2013-02-13T00:30:00

In [68]:
mod(5,5), mod1(5,5), mod(0,5), mod1(0,5)

(0, 5, 0, 5)

In [69]:
mod2pi(9*pi/4)

0.7853981633974481

In [70]:
gcd(6,9), lcm(2,3)

(3, 6)

In [71]:
∛3 # \cbrt

1.4422495703074083

In [72]:
hypot(2, 3)

3.6055512754639896

In [73]:
significand(15.2)/15.2

0.125

In [74]:
?sinpi

search: sinpi



```
sinpi(x)
```

Compute $\sin(\pi x)$ more accurately than `sin(pi*x)`, especially for large `x`.


In order to compute trigonometric functions with degrees instead of radians, suffix the function with d. For example, sind(x) computes the sine of x where x is specified in degrees. 

In [76]:
real(1 + 2im), imag(1 + 2im), conj(1 + 2im)

(1, 2, 1 - 2im)

In [77]:
numerator(2//3), denominator(2//3)

(2, 3)

### Strings

In [83]:
'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [81]:
typeof(ans)

Char

In [86]:
Int('x'), typeof(Int('x'))

(120, Int64)

In [88]:
Char(0x110000) # no automatic check

'\U110000': Unicode U+110000 (category Cn: Other, not assigned)

In [90]:
isvalid(Char, 0x110000)

false

In [93]:
'A' < 'a', 'x' - 'a', 'A' + 1

(true, 23, 'B')

In [94]:
"""Contains "quote" characters"""

"Contains \"quote\" characters"

In [99]:
str = "Hello, world.\n"
str[1], str[end], str[end-1], str[end÷2], str[4:9], str[2:2]

('H', '\n', '.', ' ', "lo, wo", "e")

In [100]:
# ↑ note type Char for single indices

#### Iteration

In [101]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [103]:
s[1]

'∀': Unicode U+2200 (category Sm: Symbol, math)

In [102]:
s[2]

LoadError: UnicodeError: invalid character index

In [104]:
nextind(s,1)

4

In [107]:
for i = 1:endof(s)
   try
       print(s[i])
   catch
       # ignore the index error
   end
end

∀ x ∃ y

In [106]:
# iterating handles invalid indices
for c in s
   print(c)
end

∀ x ∃ y

#### Concatenation & Interpolation

In [111]:
# Concatenation
greet = "Hello"; whom = "world"

"world"

In [109]:
string(greet, ", ", whom, ".\n")

"Hello, world.\n"

In [110]:
greet * ", " * whom * ".\n"

"Hello, world.\n"

In [112]:
"$greet, $whom.\n"

"Hello, world.\n"

In [113]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [116]:
print("I have \$100 in my account.\n")

I have $100 in my account.


#### Triple-quotes

In [117]:
"""
hello""" # NOTE: 1 newline stripped, not more

"hello"

In [125]:
# Triple-quoted strings are also dedented to the level 
# of the least-indented line. 
str = """
    Hello,
    world.
  """ # -> those whitespaces at the beginning count

"  Hello,\n  world.\n"

####

In [126]:
"abracadabra" < "xylophone"

true

In [128]:
search("xylophone", 'x'), search("xylophone", 'o', 5)

(1, 7)

In [130]:
contains("Hello, world.", "world")

true

In [131]:
'o' in "xylophone"  # required for Char

true

In [132]:
?count

search: count countnz countlines count_ones count_zeros codeunit checkbounds



```
count(p, itr) -> Integer
count(itr) -> Integer
```

Count the number of elements in `itr` for which predicate `p` returns `true`. If `p` is omitted, counts the number of `true` elements in `itr` (which should be a collection of boolean values).

```jldoctest
julia> count(i->(4<=i<=6), [2,3,4,5,6])
3

julia> count([true, false, true, true])
3
```


In [133]:
repeat(".:Z:.", 10)

".:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:..:Z:."

In [134]:
join(["apples", "bananas", "pineapples"], ", ", " and ")

"apples, bananas and pineapples"

In [138]:
?less

search: less @less isless lexless filesize values falses sylvester



```
less(file::AbstractString, [line::Integer])
```

Show a file using the default pager, optionally providing a starting line number. Returns to the `julia` prompt when you quit the pager.

```
less(function, [types])
```

Show the definition of a function using the default pager, optionally specifying a tuple of types to indicate which method to see.


#### Regex

In [140]:
r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [141]:
typeof(ans)

Regex

In [142]:
ismatch(r"^\s*(?:#|$)", "not a comment")

false